version: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: cd nextjs_TS && npm install

      - run:
          name: Build Static App
          command: cd nextjs_TS && npm run export

      - run:
          name: Run Tests
          command:  echo "no tests"

  deploy:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Install Dependencies
          command: cd nextjs_TS && npm install

      - run:
          name: Build Static App
          command: cd nextjs_TS && npm run export

      - run:
          name: Deploy to Webserver
          command: cd nextjs_TS && ./deploy.sh

