version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: cd nextjs_TS && yarn

      - run:
          name: Build Static App
          command: cd nextjs_TS && yarn run export

      - run:
          name: Run Tests
          command:  echo "no tests"

  build_docker:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t $DOCKER_REPO:$CIRCLE_BRANCH . 
      - run:
          name: Push to Docker Hub
          command: |
            docker login --username $DOCKER_USER --password $DOCKER_PASSWORD 
            docker tag anypay $DOCKER_REPO:$CIRCLE_BRANCH
            docker push $DOCKER_REPO:$CIRCLE_BRANCH

  deploy:
    machine: true
    steps:
      - run:
          name: Deploy to Web Servers
          command: ssh root@anypayx.com "sudo chef-client -o recipe[anypayx.com]"

  deploy_next:
    machine: true
    steps:
      - run:
          name: Deploy Next Branch To Next Web Server
          command: ssh root@next.anypayx.com "sudo chef-client -o recipe[anypay.com::next]"



workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - build_docker:
          requires:
            - build
      - deploy:
          requires:
            - build_docker
          filters:
            branches:
              only:
                - master
      - deploy_next:
          requires:
            - build_docker
          filters:
            branches:
              only:
                - next

