version: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: master

jobs:
  build_and_deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: cd nextjs_TS && npm install

      - run:
          name: Build Static App
          command: cd nextjs_TS && npm run export

      - run:
          name: Run Tests
          command:  echo "no tests"

      - run:
          name: Deploy to Webserver
          command: scp -r nextjs_TS/_static/* ubuntu@next.anypayx.com:/opt/next.anypayx.com

